#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, then you must set SHELL to a compliant shell.
#
#   (2) You need the command "locale" (usually in package "locales" or "gettext") to
#       be present and working on your system.
#
#   Important for patching:
#
#   (1) This script is generated from the template file
#       software/grADle-launcher/src/main/java/org/gradle/jvm/internal/PosixStartScriptTemplate.java
#       within the Gradle project.
#
#   (2) Please make sure to keep this script compatible with POSIX.
#       Don't use bashisms nor GNU getopt features.
#
#   (3) Changes to this file should also be synchronized to the template file.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# Change from the symlink's directory to the real installation directory
cd "${APP_HOME:-./}" > /dev/null || exit 1

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo >&2 "$*"
}

die () {
    echo >&2 "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit: $MAX_FD"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit: $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS
#   * -jar __INIT__ for the gradle-wrapper.jar
#
# Collating them in reverse order means they'll be in the right order when we're through.
# (see http://tenet.das.ufsc.br/~edson/disciplinas/sistemas-distribuidos/bash-options.html for an explanation of the technique)

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                           # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}            # looks like a POSIX filepath
                    [ -e "$t" ] ;;                    #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `eval b=c` sets c in the current shell, however a `eval b=c`
        # inside a `for` loop will set c in the subshell, thus `b` will not be
        # set in the current shell. So we need to eval the result to set the
        # positional parameters in the current shell:
        # shellcheck disable=SC2039,SC3044
        eval 'set -- "${@#"$1"}" "$arg"'
    done
fi

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, if any
#   * Groovy's various -D settings
#   * -jar __INIT__ for the gradle-wrapper.jar
#   * remaining arguments from the command line
# shellcheck disable=SC2145
eval set -- \
    "$DEFAULT_JVM_OPTS" \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args correctly and to apply the arg limit.
# (The latter is needed on some systems because exec has a limited command line length.)
# NOTE: Using null as delimiter (instead of newline) to better support paths with newlines.
printf '%s\0' "$@" | xargs -0 -n 100000 exec "$JAVACMD"